[settings.python]
compile = false

[settings.pipx]
uvx = true

[settings.node]
compile = false

[tools]
# global tool versions go here
# you can set these with `mise use -g`

fzf = "latest"
ghq = "latest"


# Programming Languages
## Python
uv = "latest"

## Golang
golang = "latest"

## Node.js
nodejs = "lts"

# CLI Tools
## AWS CLI
awscli = "latest"

# GitHub CLI
gh = "latest"

# GitLab CLI
glab = "latest"
