[settings.python]
compile = false

[settings.pipx]
uvx = true

[settings.node]
compile = false

[tools]
# global tool versions go here
# you can set these with `mise use -g`

fzf = "latest"

# Python
uv = 'latest'

# Golang
golang = 'latest'

# Node.js

nodejs = 'lts'

# AWS CLI
awscli = 'latest'
