[settings.pipx]
uvx = true

[tools]
# global tool versions go here
# you can set these with `mise use -g`

fzf = "latest"

# Python
uv = 'latest'

# Golang
golang = 'latest'

# Node.js
nodejs = 'lts'
